import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar/page";
import Footer from "./component/Footer/page";
import { BooksProvider } from "./../context/page";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next js 1st web",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/book.ico",
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Wrap your app in the new ToastProvider */}

        <BooksProvider>
          <Navbar />

          <main>{children}</main>
          <Footer />
          <ToastContainer />
        </BooksProvider>
      </body>
    </html>
  );
}
